# Working with numpy


In [7]:
import numpy as np


### Working with Arrays in numpy 


In [9]:
import numpy as np
my_array=np.array([[13,3,4,5],[7,4,4,35]]) #2d array
print("my 2d array is ",my_array)
one_matrix = np.ones((3,3)) # one matrix that have 3x3 dimintion
print(one_matrix) 
null_matrix = np.zeros((3,3)) # null matrix that have 3x3 dimintion
print(null_matrix) 
random_matrix = np.random.randn(3,3) # random_matrix that have 3x3 dimintion
print(random_matrix) 

my 2d array is  [[13  3  4  5]
 [ 7  4  4 35]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 0.81580025 -0.37047454  2.23403908]
 [ 1.82269532 -0.78013426 -0.89620195]
 [ 1.85838779  0.11589876  1.07101062]]


### Array properties

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)          # (2, 3) — dimensions
print(arr.dtype)          # data type (int, float, etc.)
print(arr.ndim)           # number of dimensions
print(arr.size)           # total number of elements
print(len(arr) )

(2, 3)
int64
2
6
2


### operation and  Accessing the elem

In [10]:
print(my_array[0]) # This will print first row of matrix 
print(my_array[0,3]) # This will print the 0,3 elem of matrix
print(my_array+4) #ading 4 to all elem of my_array

[13  3  4  5]
5
[[17  7  8  9]
 [11  8  8 39]]
