## Phase1 : Basics SVD Martix

In [7]:
import numpy as np

A = np.array([[12,4,55],[23,42,5],[23,53,66]],dtype="float")

print("shape of A Matrix",A.shape)
print("Vale of A matrix \n", A)
U,S,Vt= np.linalg.svd(A,full_matrices=True) # Calling linear Algbera module from numpy

print("The value of U(left singular vactor) is \n ", U)
print("The value of S(Singluar value) is \n ", S)
print("The value of Vt(Right singluar vactor) is \n ", Vt)
Sigma = np.zeros(A.shape)
Sigma[:min(A.shape), :min(A.shape)] = np.diag(S)

# Reconstruct
A_reconstructed = U @ Sigma @ Vt

print("\nReconstructed A:")
print(A_reconstructed)

print("\nReconstruction error:")
print(np.allclose(A, A_reconstructed)) # Should print True

shape of A Matrix (3, 3)
Vale of A matrix 
 [[12.  4. 55.]
 [23. 42.  5.]
 [23. 53. 66.]]
The value of U(left singular vactor) is 
  [[-0.45617058  0.65357275 -0.60394624]
 [-0.32552183 -0.7541908  -0.57029095]
 [-0.82821733 -0.06355227  0.55679185]]
The value of S(Singluar value) is 
  [105.71027796  44.21405052   8.21309138]
The value of Vt(Right singluar vactor) is 
  [[-0.30280923 -0.56183863 -0.7698337 ]
 [-0.24800301 -0.73347709  0.63285533]
 [-0.92021795  0.38255551  0.08276596]]

Reconstructed A:
[[12.  4. 55.]
 [23. 42.  5.]
 [23. 53. 66.]]

Reconstruction error:
True
